name: Reusable Kubernetes Deploy

on:
  workflow_call:
    inputs:
      manifests_path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f ${{ inputs.manifests_path }}
