name: EKS AMI Update

on:
  #schedule:
  #  - cron: "0 3 * * 1" # Every Monday
  workflow_dispatch:

jobs:
  update-eks-ami:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
